
[general]
	terror_hydra_strike_hud = true
	terror_hydra_hud = true
	crimson_dominus_hud = true
	equipment_hud = true
	armor_hud = true

[kuudra]

	[kuudra.dropship_warning]
		dropship_warning = true
		warning_time = 5

	[kuudra.kuudra_profit]
		kuudra_profit_display = true

	[kuudra.energized_chunk]
		energized_chunk_warning = true

[hud]

	[hud.flare_timer]
		flare_timer = true

	[hud.dropship_warning]
		dropship_warning = true
		warning_time = 5

	[hud.reaper_armor_cooldown]
		reaper_armor_cooldown_hud = true
		only_show_with_ragnarock_axe = true

	[hud.soulflow]
		soulflow_hud = true

	[hud.item_cooldown]
		ragnarock_axe_cooldown_hud = true

	[hud.kuudra_profit]
		kuudra_profit_display = true

	[hud.general_hud]
		reforge_hud = true
		equipment_hud = true
		armor_hud = true

	[hud.kuudra_armor_hud]
		terror_hydra_strike_hud = true
		crimson_dominus_hud = true

	[hud.lifeline_display]
		lifeline_hud = true
		"only_show_when_in_kuudra's_hollow" = false

	[hud.inventory]
		inventory_hud_color = "76,224,201,201"
		inventory_hud = true

	[hud.last_breath_hud]
		last_breath_reset_length = 10
		only_show_when_in_hotbar = true
		last_breath_hotbar_only = true
		last_breath_hit_count_hud = true
		only_show_when_last_breath_is_in_hotbar = true

	[hud.ragaxe_cooldown]
		only_show_when_ragnarock_axe_is_in_hotbar = true
		ragnarock_axe_cooldown_hud = true
		only_show_when_in_hotbar = true
		ragnarock_axe_hotbar_only = true

	[hud.composter]
		composter_time_hud = false

[dungeon]

	[dungeon.m7_terminal]
		waypoint_color = "255,255,0,0"
		terminal_waypoint_color = "255,255,0,0"
		second_terminal_class = 1
		m7_terminal_waypoint = true
		first_terminal_class = 0
		fourth_terminal_class = 3
		third_terminal_class = 2

	[dungeon.relic_waypoint]
		relic_waypoint = true

